hbase-site.xml:
    dfs.datanode.socket.write.timeout: 600000
    dfs.socket.timeout: 600000
    hbase.client.pause: 10000
    hbase.client.retries.number: 20
    hbase.client.write.buffer: 2097152
    hbase.cluster.distributed: "true"
    hbase.coprocessor.master.classes: org.apache.hadoop.hbase.security.access.AccessController
    hbase.coprocessor.region.classes: org.apache.hadoop.hbase.security.token.TokenProvider,org.apache.hadoop.hbase.security.access.AccessController
    hbase.hregion.majorcompaction: 604800000
    hbase.hregion.max.filesize: 10147483648
    hbase.hregion.memstore.flush.size: 134217728
    hbase.master.balancer.stochastic.readRequestCost: 150
    hbase.master.balancer.stochastic.regionCountCost: 200
    hbase.master.balancer.stochastic.writeRequestCost: 150
    hbase.master.distributed.log.splitting: "true"
    hbase.master.info.port: 8010
    hbase.master.loadbalance.bytable: "true"
    hbase.regionserver.codecs: snappy
    hbase.regionserver.handler.count: 100
    hbase.regionserver.info.port: 8030
    hbase.regionserver.lease.period: 600000
    hbase.regionserver.thread.compaction.large: 3
    hbase.regionserver.thread.compaction.small: 3
    hbase.regionserver.thread.split: 3
    hbase.rootdir: hdfs://mycluster/hbase
    hbase.rpc.timeout: 600000
    hbase.security.authorization: "true"
    hbase.snapshot.enabled: "true"
    hbase.splitlog.max.resubmit: 10
    hbase.zookeeper.property.maxClientCnxns: 1024
    hbase.zookeeper.quorum: 1.hslave.adh,2.hslave.adh,3.hslave.adh
    zookeeper.session.timeout: 800000
